# Generated by Django 5.1.1 on 2024-09-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('last_name', models.CharField(max_length=80, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('service', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
