# Generated by Django 5.1.1 on 2024-09-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='hour',
            new_name='end_hour',
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_hour',
            field=models.TimeField(max_length=250, null=True),
        ),
    ]
