# Generated by Django 5.1.1 on 2024-09-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('start_hour', 'end_hour'), name='unique_hour')],
            },
        ),
    ]
